# Generated by Django 3.0.5 on 2020-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='topAccomplishments',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
